# Generated by Django 2.2.6 on 2020-02-14 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0004_auto_20200214_0734'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bb',
            name='product',
        ),
    ]
