# Generated by Django 3.0.3 on 2020-02-27 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bboard', '0006_auto_20200226_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='bb',
            name='url',
            field=models.SlugField(default=''),
            preserve_default=False,
        ),
    ]
